version: '3.7'
services:
  lifedata-visualizer:
    image: lifedata-visualizer
    restart: unless-stopped
    environment:
      - DATA_DIR=${LDV_TARGET_DATA_DIR}
      - GRAPH_DIR=${LDV_TARGET_GRAPH_DIR}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - port=${LDV_PORT}
        - uid=${LDV_UID}
        - user=${LDV_USER}
        - gid=${LDV_GID}
        - group=${LDV_GROUP}
    user: "${LDV_USER}:${LDV_GROUP}"
    ports:
      - "127.0.0.1:${LDV_PORT}:${LDV_PORT}"
    volumes:
      - type: bind
        source: ${LDV_SOURCE_GRAPH_DIR}
        target: ${LDV_TARGET_GRAPH_DIR}
        read_only: false
      - type: bind
        source: ${LDV_SOURCE_DATA_DIR}
        target: ${LDV_TARGET_DATA_DIR}
        read_only: true
