version: '3.7'
services:
  lifedata-graph-generator:
    image: lifedata-graph-generator
    restart: unless-stopped
    environment:
      - DATA_DIR=${LDV_GENERATOR_TARGET_DATA_DIR}
      - GRAPH_DIR=${LDV_GENERATOR_TARGET_GRAPH_DIR}
    build:
      context: ./graph-generator/
      dockerfile: Dockerfile
      args:
        - uid=${LDV_GENERATOR_UID}
        - user=${LDV_GENERATOR_USER}
        - gid=${LDV_GENERATOR_GID}
        - group=${LDV_GENERATOR_GROUP}
    user: "${LDV_GENERATOR_USER}:${LDV_GENERATOR_GROUP}"
    volumes:
      - type: bind
        source: ${LDV_GENERATOR_SOURCE_GRAPH_DIR}
        target: ${LDV_GENERATOR_TARGET_GRAPH_DIR}
        read_only: false
      - type: bind
        source: ${LDV_GENERATOR_SOURCE_DATA_DIR}
        target: ${LDV_GENERATOR_TARGET_DATA_DIR}
        read_only: true

  lifedata-web-server:
    image: lifedata-web-server
    restart: unless-stopped
    environment:
      - SERVE_DIR=${LDV_SERVER_TARGET_SERVE_DIR}
    build:
      context: ./web-server/
      dockerfile: Dockerfile
      args:
        - port=${LDV_SERVER_PORT}
        - uid=${LDV_SERVER_UID}
        - user=${LDV_SERVER_USER}
        - gid=${LDV_SERVER_GID}
        - group=${LDV_SERVER_GROUP}
    user: "${LDV_SERVER_USER}:${LDV_SERVER_GROUP}"
    ports:
      - "127.0.0.1:${LDV_SERVER_PORT}:${LDV_SERVER_PORT}"
    volumes:
      - type: bind
        source: ${LDV_SERVER_SOURCE_SERVE_DIR}
        target: ${LDV_SERVER_TARGET_SERVE_DIR}
        read_only: true

